### PR TITLE
State*2policy functions for CLatticeParameters

### PR DESCRIPTION
**Pull request by michalkoziarski**
Time spent:
- writing functions: 2-3 minutes,
- debugging why this doesn't work (spoiler: due to function conversions inherited from Cube): ungodly amount of time.

### CODE REVIEW

**Comment by alexhernandezgarcia** [comment]
Sorry to hear this has been painful :( So it doesn't work yet or does it?

**Comment by michalkoziarski** [comment]
It should be working! I am re-fitting dummy proxy to run a test training right now.

**Comment by alexhernandezgarcia** [comment]
> It should be working! I am re-fitting dummy proxy to run a test training right now (which will be a more comprehensive test).

Ah perfect! I was confused by the present tense "why this doesn't work" 

I'd be curious to hear what the issue was btw.

**Comment by michalkoziarski** [comment]
> I'd be curious to hear what the issue was btw.
It was stupid, really. Wrote `state2proxy`, tried to test it, but the output was consistently different than just executing the identical code, but outside the function. I was wondering if I am going insane, but it turns out `Cube` just has all of these conversions, so you can't simply overwrite `state2proxy`, as it will be assigned `state2policy` in `super` anyway (which is inherited)...

FYI, I am simply using the same output for all `*2proxy`, `*2oracle` and `*2policy` not to deal with this, hoping that the policy can handle wider range of values (discrete env does train w.r.t. correlation).

**Review by alexhernandezgarcia — COMMENTED** [review]
Looks good, will merge.

**Pull request merged**
