### PR TITLE
License and citation files

### PR DESCRIPTION
**Pull request by alexhernandezgarcia**
This PR adds a license file and a citation file.

License: Attribution-NonCommercial-ShareAlike 4.0 International ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/))

Citation: [.cff format](https://citation-file-format.github.io), created with [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/).

### CODE REVIEW

**Comment by vict0rsch** [comment]
Are you sure `Attribution-NonCommercial-ShareAlike 4.0 International` is the best way forward? 

* Besides my personal plans, it may become an issue for you if you end up having industry collaborations, this could prevent them from coding with you (`NC`)
* Even without `NC`, `CC-BY-SA` is not recommended: https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code

Apache 2.0 or MIT are more common for this type of work.

**Comment by vict0rsch** [comment]
@josephdviviano may have feedback too

**Comment by josephdviviano** [comment]
If you want this codebase to be used by those in industry for collaborations, Apache2 or MIT are the "standards".

I learned this the hard way. I accidentally blocked Flaviu from IBM from using `torchgfn` because we had a GPL license! So we switched to Apache2

**Comment by vict0rsch** [comment]
(Added a `bibtex` citation at the end of the readme with `cffconvert -f bibtex` -- see https://github.com/citation-file-format/cffconvert)

**Comment by alexhernandezgarcia** [comment]
Alright, I don't know much about licenses, but I trust you all. Also, Pierre Luc needs a less restrictive license too to be able to contribute.

I have replaced the license file by an Apache 2.0 one.

**Comment by alexhernandezgarcia** [comment]
@josephdviviano feel free to add your name to the list of contributors, citation files, etc.

**Review by josephdviviano — APPROVED** [review]
lgtm

**Comment by josephdviviano** [comment]
merging to ensure tests pass (we can do this for all PRs going forward)

**Pull request merged**
